# 샘플 설정 파일 - 실제 사용 전 복사하여 수정하세요
# cp sample_config.yaml dev_config.yaml 또는 prod_config.yaml

# 텔레그램 설정
telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"
  quiet_hours:
    start: "22:00"  # 저녁 10시
    end: "08:00"    # 아침 8시

# Upbit API 설정
upbit:
  access_key: "YOUR_UPBIT_ACCESS_KEY"
  secret_key: "YOUR_UPBIT_SECRET_KEY"

# 한국투자증권 API 설정
kis:
  access_key: "YOUR_KIS_ACCESS_KEY"
  secret_key: "YOUR_KIS_SECRET_KEY"
  account_number: "YOUR_ACCOUNT_NUMBER"
  account_code: "01"  # 상품코드 (01: 주식, 02: 선물옵션)

# 리스크 관리 설정
risk:
  stop_loss_percent: 3       # 기본 손절 비율 (%)
  stop_loss_percent_high: 2  # 최고가 대비 손절 비율 (%)
  max_investment_per_trade: 100000  # 거래당 최대 투자금액 (원)
  max_daily_loss: 50000      # 일일 최대 손실 금액 (원)

# 전략 설정
strategy:
  rsi_period: 14          # RSI 기간
  macd_fast: 12           # MACD 빠른선
  macd_slow: 26           # MACD 느린선
  macd_signal: 9          # MACD 시그널
  desc: "전략적으로 3% 손절 후 매매 횟수 최대화"

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_rotation: "daily"  # daily, size
  max_size_mb: 10  # size 로테이션 사용 시 최대 파일 크기 (MB)
  backup_count: 30  # 보관할 로그 파일 수
  output: ["file", "console"]  # 로그 출력 대상 (file, console)

# 대시보드 설정
dashboard:
  port: 8501
  refresh_interval: 60  # 초 단위
  theme: "light"  # light, dark

# 데이터베이스 설정 (Supabase)
database:
  url: "YOUR_SUPABASE_URL"
  key: "YOUR_SUPABASE_KEY"
  table_prefix: "jats_" 